### ISSUE TITLE
Cache misses due to path-based versioning and its normalization

### ISSUE THREAD

**Issue by mzabaluev** [actions/cache#330]
[This run](https://github.com/mzabaluev/github-actions-playground/actions/runs/116171611) using `actions/cache@v2` shows how a cache created by the `update-deps` job is not hit by the jobs in the `test` matrix that depend on `update-deps` and use the same key. This works in `actions/cache@v1`, so it looks like a regression to me.

What's more peculiar, each of the three `test` jobs reported to have successfully stored its cache state under this same key.
In the [next run](https://github.com/mzabaluev/github-actions-playground/actions/runs/116174830), all jobs hit the cache, but which state did they get?

**Comment by dhadka** [comment]
Hey @mzabaluev, thanks for spotting this.  Can you please enable [step debugging](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-debug-logging), change the key, and re-run the workflow?  This will provide some more output so we can see what's going on.

**Comment by mzabaluev** [comment]
@dhadka [Here you are](https://github.com/mzabaluev/github-actions-playground/actions/runs/116368502)

I see that the 'Post Cache cargo registry index' step in the producer job gets to write its cache first:
```
Resource Url: https://artifactcache.actions.githubusercontent.com/SwZ48ggH2fmptrBol7q4o6DwD74REZ2KvEjuDiE8Jb9dgsMc8M/_apis/artifactcache/caches/58
```

Then the 'Post Cache cargo registry' step allocates at the same resource:

```
Resource Url: https://artifactcache.actions.githubusercontent.com/SwZ48ggH2fmptrBol7q4o6DwD74REZ2KvEjuDiE8Jb9dgsMc8M/_apis/artifactcache/caches/59
```

There is also intra-action state `CACHE_KEY` which is set by the caching steps prior to the above, but in the opposite order:

```
2020-05-27T02:11:21.4628234Z ##[debug]Save intra-action state CACHE_KEY = cargo-registry-debug1-39f2b8d68761c35ef5f7317c495a2e84f0aed5d34a5d724b2144d58bf6ed66b3
...
2020-05-27T02:11:22.0139963Z ##[debug]Save intra-action state CACHE_KEY = cargo-index-debug1-5d9c7f87b512b22e0543a050c81e91b650b44aff
```

A consumer job queries and fails with:

```
Resource Url: https://artifactcache.actions.githubusercontent.com/SwZ48ggH2fmptrBol7q4o6DwD74REZ2KvEjuDiE8Jb9dgsMc8M/_apis/artifactcache/cache?keys=cargo-registry-debug1-39f2b8d68761c35ef5f7317c495a2e84f0aed5d34a5d724b2144d58bf6ed66b3&version=55646160c9f2cc2a37adf24b94db1ec7546d85f0e81c7dde1c978bdca39a013e
```

Then in the 'Post Cache cargo registry' step, it saves a new value:

```
Resource Url: https://artifactcache.actions.githubusercontent.com/SwZ48ggH2fmptrBol7q4o6DwD74REZ2KvEjuDiE8Jb9dgsMc8M/_apis/artifactcache/caches/60
```

**Comment by dhadka** [comment]
@mzabaluev I think I see what's going on.  @v2 introduced a `version` field, which is used to detect when the configuration of the cache action changes.  This includes what kind of compression it's using (gzip vs zstd) and the `path`.  From what I see, `update-deps` is using the path

```
  with:
    path: ~/.cargo/registry
          !~/.cargo/registry/src
```

whereas the `test` step is using:

```
  with:
    path: ~/.cargo/registry
```

If you make the `path` identical in both, you should see it behave as expected.

This was intended to prevent a user from changing the path but using the same key, since the existing cache entry (if any) wouldn't have the right content.  However, in your particular case where you're just excluding a path, it's less helpful.

**Comment by mzabaluev** [comment]
@dhadka
> If you make the `path` identical in both, you should see it behave as expected.

On Linux and Mac it does, on Windows it doesn't: https://github.com/mzabaluev/github-actions-playground/actions/runs/116588403

I'm guessing that CRLF line endings screw up the version hash.
Consider making the normalization function invariant to whitespace separating the paths, including any line ending characters. The `path` parameter really could help accepting a list, but I gather that https://github.com/actions/toolkit/issues/184 is preventing that.

**Comment by mzabaluev** [comment]
For more fun with cache key normalization across OSes, see https://github.com/actions/runner/issues/498

**Comment by mzabaluev** [comment]
Any updates on this?

I'm trying to decide which `actions/cache` version is a less buggy fit for our needs, between this and v1 somehow [failing](https://github.com/input-output-hk/chain-libs/runs/730161000?check_suite_focus=true) to hit the primary key and going for a truncated key it has somehow stored at some point, despite not being given any `restore-keys` to try prefix searching.

**Comment by dhadka** [comment]
@mzabaluev I don't think this is related to newlines, since both Windows and Linux are reading from the same file, so the line endings wouldn't be changing.  Your issue about new lines and `hashFiles` is valid, however, since the newlines are being changed by Git.

I suspect this is the result of https://github.com/actions/cache/issues/301.  There's an issue with Windows bsd tar and zstd causing it to hang, so it falls back to gzip compression.

**Comment by dhadka** [comment]
@mzabaluev I've created this PR to trim any leading and trailing whitespace from the path and restore keys, which would also remove any leftover Windows newline characters (`\r`) after the split - https://github.com/actions/cache/pull/343.  However, as I mentioned in the previous comment, I don't think newlines are causing the issue you see since the yml files don't change across OSes.

**Comment by dhadka** [comment]
@mzabaluev Agreed.  I meant to say that #343 will fix any newline differences in the path which would cause a different version hash, but you'll likely still see Windows creating a different cache because it uses a different compression method.

The version hash [includes the compression method](https://github.com/actions/toolkit/blob/9ba7c679ad74f6a80017feeb94b7a7c19b590796/packages/cache/src/internal/cacheHttpClient.ts#L94), but we [fall back to using Gzip on Windows](https://github.com/actions/toolkit/blob/9ba7c679ad74f6a80017feeb94b7a7c19b590796/packages/cache/src/internal/cacheUtils.ts#L86) due to bug #301.

**Comment by mzabaluev** [comment]
> The version hash [includes the compression method](https://github.com/actions/toolkit/blob/9ba7c679ad74f6a80017feeb94b7a7c19b590796/packages/cache/src/internal/cacheHttpClient.ts#L94), but we [fall back to using Gzip instead of Zstd on Windows](https://github.com/actions/toolkit/blob/9ba7c679ad74f6a80017feeb94b7a7c19b590796/packages/cache/src/internal/cacheUtils.ts#L86) due to bug #301.

I hope in the end state it would be possible to share cache state no matter which runner created it, with the restore action being able to adapt to a possibly different archival format; or maybe this and [other tar-related issues](https://github.com/actions/toolkit/issues/479) will be solved by settling on a single flavor of tar that works across all OSes. The disparate cache entries for Windows and Unix would increase our cache pressure twofold and duplicate the dependency fetching work for Windows jobs without a good reason for it.

**Comment by mzabaluev** [comment]
Yes, we still need tar in the cache action to be fixed.

**Comment by pdotl** [comment]
👋 @mzabaluev we are currently looking into this. For now you could try [this](https://github.com/actions/cache/blob/main/workarounds.md#improving-cache-restore-performance-on-windowsusing-cross-os-caching) approach if it works for you.

**Comment by y-nk** [comment]
I created this repo to illustrate the issue i'm having which is related to this bug.

https://github.com/y-nk/cache-in-container/actions/runs/3427866818

The problem being that an action building outside of a container has a certain path, and so that path cannot be restored once inside a container (bc the context of the container is different)

**Comment by pdotl** [comment]
@mzabaluev @y-nk we are tracking this issue in #984. Please check the current proposal there and provide comments/feedback if any. Closing this as duplicate.

**Comment by Phantsure** [comment]
@mzabaluev @y-nk We have released a new beta release which should fix this issue. Try tag: `actions/cache@3.1.0-beta`. Head over to discussion for feedback: https://github.com/actions/cache/discussions/1019

**Comment by mzabaluev** [comment]
With `actions/cache@v3`, a cache key is hit on Windows after being created on Linux.

As evidenced in this workflow (it still fails, but due to an evident problem with the installation of Cargo): https://github.com/mzabaluev/github-actions-playground/actions/runs/3783738410/jobs/6432524102
